plugins { id 'com.android.application' }

android {
    namespace 'ps.man.water'
    compileSdk 35

    defaultConfig {
        applicationId 'ps.man.water'
        minSdk 26
        targetSdk 35
        versionCode 204
        versionName '2.0.4'
    }

    buildTypes {
        release { minifyEnabled false }
        debug { applicationIdSuffix '.debug'; versionNameSuffix '-debug' }
    }
}
