package ps.man.water;
import android.Manifest;import android.annotation.SuppressLint;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.media.RingtoneManager;import android.net.Uri;import android.os.*;import android.webkit.*;import java.io.*;import java.net.*;import org.json.*;
public class MainActivity extends Activity{
 private WebView web;private final BroadcastReceiver updates=new BroadcastReceiver(){public void onReceive(Context c,Intent i){refresh();}};
 @SuppressLint("SetJavaScriptEnabled") public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},30);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setCacheMode(WebSettings.LOAD_CACHE_ELSE_NETWORK);s.setAllowFileAccess(true);web.addJavascriptInterface(new Bridge(),"MAN");web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return false;}public void onPageFinished(WebView v,String u){refresh();}});if(b==null)web.loadUrl("file:///android_asset/offline/index.html");registerReceiver(updates,new IntentFilter(TimerService.UPDATE),Build.VERSION.SDK_INT>=33?Context.RECEIVER_NOT_EXPORTED:0);}
 private void refresh(){if(web!=null)web.post(()->web.evaluateJavascript("window.refreshNative&&window.refreshNative()",null));}
 protected void onDestroy(){try{unregisterReceiver(updates);}catch(Exception e){}super.onDestroy();}
 public void onBackPressed(){if(web!=null&&!web.getUrl().startsWith("file:///android_asset")&&web.canGoBack())web.goBack();else super.onBackPressed();}
 public class Bridge{
  @JavascriptInterface public String state(){return TimerService.snapshot(MainActivity.this).toString();}@JavascriptInterface public String archive(){return prefs().getString("archive","[]");}@JavascriptInterface public String queue(){return prefs().getString("queue","[]");}
  @JavascriptInterface public void enqueue(String n,int sec){Intent i=new Intent(MainActivity.this,TimerService.class).setAction(TimerService.ENQUEUE).putExtra("name",n).putExtra("seconds",sec);startForegroundService(i);}@JavascriptInterface public void pause(){send(TimerService.PAUSE);}@JavascriptInterface public void resume(){send(TimerService.RESUME);}@JavascriptInterface public void finish(){send(TimerService.FINISH);}@JavascriptInterface public void removeQueued(String id){startService(new Intent(MainActivity.this,TimerService.class).setAction(TimerService.REMOVE).putExtra("uuid",id));}
  @JavascriptInterface public void chooseSound(){runOnUiThread(MainActivity.this::pick);}@JavascriptInterface public void testAlert(){startForegroundService(new Intent(MainActivity.this,TimerService.class).setAction(TimerService.TEST));}@JavascriptInterface public void openOnline(){runOnUiThread(()->web.loadUrl("https://man.ps/water"));}@JavascriptInterface public String sync(){return syncNow();}private void send(String a){startService(new Intent(MainActivity.this,TimerService.class).setAction(a));}
 }
 private SharedPreferences prefs(){return getSharedPreferences("man_water",MODE_PRIVATE);}private void pick(){Intent p=new Intent(RingtoneManager.ACTION_RINGTONE_PICKER);p.putExtra(RingtoneManager.EXTRA_RINGTONE_TYPE,RingtoneManager.TYPE_NOTIFICATION);p.putExtra(RingtoneManager.EXTRA_RINGTONE_SHOW_SILENT,false);startActivityForResult(p,91);}protected void onActivityResult(int q,int r,Intent d){super.onActivityResult(q,r,d);if(q==91&&r==RESULT_OK&&d!=null){Uri u=d.getParcelableExtra(RingtoneManager.EXTRA_RINGTONE_PICKED_URI);if(u!=null)prefs().edit().putString("alert_uri",u.toString()).apply();}}
 private String syncNow(){try{JSONArray all=new JSONArray(prefs().getString("archive","[]")),items=new JSONArray();for(int i=0;i<all.length();i++)if(!all.getJSONObject(i).optBoolean("synced"))items.put(all.getJSONObject(i));if(items.length()==0)return "{\"ok\":true,\"count\":0}";HttpURLConnection c=(HttpURLConnection)new URL("https://man.ps/water?api=sync_offline").openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestProperty("Content-Type","application/json");String ck=CookieManager.getInstance().getCookie("https://man.ps/water");if(ck!=null)c.setRequestProperty("Cookie",ck);try(OutputStream o=c.getOutputStream()){o.write(new JSONObject().put("items",items).toString().getBytes("UTF-8"));}String out=read(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());JSONObject result=new JSONObject(out);if(result.optBoolean("ok")){JSONArray ids=result.optJSONArray("synced");for(int i=0;i<all.length();i++)for(int j=0;ids!=null&&j<ids.length();j++)if(all.getJSONObject(i).optString("uuid").equals(ids.optString(j)))all.getJSONObject(i).put("synced",true);prefs().edit().putString("archive",all.toString()).apply();return new JSONObject().put("ok",true).put("count",ids==null?0:ids.length()).toString();}return out;}catch(Exception e){try{return new JSONObject().put("ok",false).put("error",e.getMessage()).toString();}catch(Exception x){return "{\"ok\":false}";}}}
 private String read(InputStream in)throws IOException{if(in==null)return "{}";BufferedReader b=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l);return s.toString();}
}
