package ps.man.water;
import android.app.*;import android.content.*;import android.media.*;import android.net.Uri;import android.os.*;import java.util.*;import org.json.*;
public class TimerService extends Service{
 public static final String ENQUEUE="ENQUEUE",PAUSE="PAUSE",RESUME="RESUME",FINISH="FINISH",REMOVE="REMOVE",TEST="TEST",UPDATE="ps.man.water.UPDATE";private static final String TIMER="water_timer_v14",ALERT="water_alert_v14";private final Handler h=new Handler(Looper.getMainLooper());private Ringtone ring;private final Runnable tick=new Runnable(){public void run(){advance();h.postDelayed(this,1000);}};
 public void onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=26){NotificationManager n=getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel(TIMER,"عداد مياه المشاهرة",NotificationManager.IMPORTANCE_LOW));NotificationChannel a=new NotificationChannel(ALERT,"تنبيهات انتهاء الوقت",NotificationManager.IMPORTANCE_HIGH);a.enableVibration(true);a.setVibrationPattern(new long[]{0,400,150,400});n.createNotificationChannel(a);}}
 public int onStartCommand(Intent i,int f,int id){String a=i==null?null:i.getAction();if(ENQUEUE.equals(a)){enqueue(i.getStringExtra("name"),i.getIntExtra("seconds",60));}else if(PAUSE.equals(a))setPaused(true);else if(RESUME.equals(a))setPaused(false);else if(FINISH.equals(a))complete(true);else if(REMOVE.equals(a))remove(i.getStringExtra("uuid"));else if(TEST.equals(a)){startForeground(7,note("تجربة التنبيه"));alarm("تجربة جرس مياه المشاهرة",5);h.postDelayed(this::ensureStarted,5200);}ensureStarted();return START_STICKY;}
 private void enqueue(String name,int seconds){try{JSONArray q=arr("queue");q.put(new JSONObject().put("uuid",UUID.randomUUID().toString()).put("subscriber_name",name.trim()).put("planned_seconds",Math.max(1,seconds)).put("created_at",iso()));save("queue",q);}catch(Exception e){}broadcast();}
 private void ensureStarted(){JSONObject c=obj("current");long wait=prefs().getLong("next_at",0)-System.currentTimeMillis();if(c.length()==0&&wait<=0){JSONArray q=arr("queue");if(q.length()>0)try{c=q.getJSONObject(0);JSONArray rest=new JSONArray();for(int j=1;j<q.length();j++)rest.put(q.get(j));c.put("start_at",iso()).put("end_epoch",System.currentTimeMillis()+c.getLong("planned_seconds")*1000).put("paused",false).put("paused_left",0).put("fired90",false).put("fired60",false);save("queue",rest);saveObj("current",c);}catch(Exception e){}}c=obj("current");if(c.length()>0){startForeground(7,note("العداد يعمل"));h.removeCallbacks(tick);h.post(tick);}else if(wait>0){startForeground(7,note("المشترك التالي خلال "+Math.max(1,wait/1000)+" ثوانٍ"));h.postDelayed(()->{prefs().edit().remove("next_at").apply();ensureStarted();},wait);}else stopSelf();broadcast();}
 private void advance(){JSONObject c=obj("current");if(c.length()==0){ensureStarted();return;}if(c.optBoolean("paused")){notifyTimer(c,"متوقف مؤقتاً");return;}long left=Math.max(0,(c.optLong("end_epoch")-System.currentTimeMillis()+999)/1000);try{if(left<=90&&!c.optBoolean("fired90")&&c.optLong("planned_seconds")>=90){c.put("fired90",true);saveObj("current",c);alarm("تبقى دقيقة ونصف — "+c.optString("subscriber_name"),5);}if(left<=60&&!c.optBoolean("fired60")&&c.optLong("planned_seconds")>=60){c.put("fired60",true);saveObj("current",c);alarm("تبقت دقيقة واحدة — "+c.optString("subscriber_name"),5);}}catch(Exception e){}if(left<=0){alarm("انتهى الوقت — "+c.optString("subscriber_name"),5);complete(false);}else notifyTimer(c,"متبقّي "+fmt(left));broadcast();}
 private void complete(boolean manual){JSONObject c=obj("current");if(c.length()>0)try{long now=System.currentTimeMillis(),planned=c.optLong("planned_seconds"),seconds=manual?Math.max(1,planned-Math.max(0,(c.optLong("end_epoch")-now)/1000)):planned;JSONObject done=new JSONObject(c.toString()).put("end_at",iso()).put("seconds",seconds).put("paused_seconds",0).put("pump_id",1).put("synced",false);JSONArray ar=arr("archive");ar.put(done);save("archive",ar);prefs().edit().remove("current").putLong("next_at",now+10000).apply();}catch(Exception e){}h.removeCallbacks(tick);broadcast();h.postDelayed(()->{prefs().edit().remove("next_at").apply();ensureStarted();},10000);}
 private void setPaused(boolean p){JSONObject c=obj("current");if(c.length()==0)return;try{if(p&&!c.optBoolean("paused")){c.put("paused_left",Math.max(0,(c.optLong("end_epoch")-System.currentTimeMillis()+999)/1000)).put("paused",true);}else if(!p&&c.optBoolean("paused")){c.put("end_epoch",System.currentTimeMillis()+c.optLong("paused_left")*1000).put("paused",false);}saveObj("current",c);}catch(Exception e){}broadcast();}
 private void remove(String id){JSONArray q=arr("queue"),n=new JSONArray();for(int x=0;x<q.length();x++){JSONObject o=q.optJSONObject(x);if(o!=null&&!id.equals(o.optString("uuid")))n.put(o);}save("queue",n);broadcast();}
 public static JSONObject snapshot(Context x){SharedPreferences p=x.getSharedPreferences("man_water",MODE_PRIVATE);try{JSONObject c=new JSONObject(p.getString("current","{}"));long left=c.length()==0?0:(c.optBoolean("paused")?c.optLong("paused_left"):Math.max(0,(c.optLong("end_epoch")-System.currentTimeMillis()+999)/1000));return new JSONObject().put("current",c).put("left",left).put("next_at",p.getLong("next_at",0));}catch(Exception e){return new JSONObject();}}
 private Notification note(String t){return build(TIMER,"مياه المشاهرة",t,true);}private void notifyTimer(JSONObject c,String t){getSystemService(NotificationManager.class).notify(7,build(TIMER,c.optString("subscriber_name","مياه المشاهرة"),t,c.length()>0));}private Notification build(String ch,String title,String text,boolean ongoing){PendingIntent p=PendingIntent.getActivity(this,1,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,ch).setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle(title).setContentText(text).setContentIntent(p).setOngoing(ongoing).setPriority(Notification.PRIORITY_MAX).setCategory(Notification.CATEGORY_ALARM).build();}
 private void alarm(String text,int sec){getSystemService(NotificationManager.class).notify((int)(System.currentTimeMillis()%100000),build(ALERT,"تنبيه العداد",text,false));AudioManager a=getSystemService(AudioManager.class);int old=a.getStreamVolume(AudioManager.STREAM_NOTIFICATION);a.setStreamVolume(AudioManager.STREAM_NOTIFICATION,a.getStreamMaxVolume(AudioManager.STREAM_NOTIFICATION),0);try{String u=prefs().getString("alert_uri",null);ring=RingtoneManager.getRingtone(this,u==null?RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION):Uri.parse(u));if(Build.VERSION.SDK_INT>=28)ring.setLooping(true);ring.play();h.postDelayed(()->{if(ring!=null)ring.stop();a.setStreamVolume(AudioManager.STREAM_NOTIFICATION,old,0);},sec*1000L);}catch(Exception e){a.setStreamVolume(AudioManager.STREAM_NOTIFICATION,old,0);}}
 private SharedPreferences prefs(){return getSharedPreferences("man_water",MODE_PRIVATE);}private JSONArray arr(String k){try{return new JSONArray(prefs().getString(k,"[]"));}catch(Exception e){return new JSONArray();}}private JSONObject obj(String k){try{return new JSONObject(prefs().getString(k,"{}"));}catch(Exception e){return new JSONObject();}}private void save(String k,JSONArray v){prefs().edit().putString(k,v.toString()).apply();}private void saveObj(String k,JSONObject v){prefs().edit().putString(k,v.toString()).apply();}private void broadcast(){sendBroadcast(new Intent(UPDATE).setPackage(getPackageName()));}private String iso(){return new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.US).format(new Date());}private String fmt(long s){return String.format(Locale.US,"%02d:%02d:%02d",s/3600,(s%3600)/60,s%60);}@Override public IBinder onBind(Intent i){return null;}
}
